import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'connectToInternet': 'Please connect to the internet',
      'offlineModeWarning': 'This feature requires an internet connection',
      'yourVacancy': 'This is your vacancy',
      'apply': 'Apply',
      'views': 'Views',
      'applications': 'Applications',
      'appliedJobs': 'Applied Jobs',
      'noApplications': 'No applications submitted yet',
      'submittedAt': 'Submitted At',
      'coverLetter': 'Cover Letter',
      'resumeLink': 'Resume Link',
      'confirmDelete': 'Confirm Deletion',
      'deleteJobConfirmation': 'Are you sure you want to delete this job?',
      'jobDeleted': 'Job deleted successfully',
      'signOut': 'Sign Out',
      'appTitle': 'Job Recruitment Platform',
      'welcomeBack': 'Welcome Back!',
      'login': 'Login',
      'signUp': 'Sign Up',
      'aboutTheApp': 'About the App',
      'help': 'Help',
      'settings': 'Settings',
      'language': 'Language',
      'requestsProcessedSuccess': 'Your requests were successfully processed',
      'darkTheme': 'Dark Theme',
      'logout': 'Logout',
      'confirmLogout': 'Confirm Logout',
      'confirmLogoutMessage': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'logoutFailed': 'Failed to log out. Please try again.',
      'contactSupport': 'Contact Support',
      'jobSeekerDashboard': 'Job Seeker Dashboard',
      'recentJobs': 'Recent Jobs',
      'jobCategories': 'Job Categories',
      'noRecentJobs': 'No recently viewed jobs',
      'email': 'Email',
      'password': 'Password',
      'enterEmail': 'Please enter your email',
      'enterPassword': 'Please enter your password',
      'invalidCredentials': 'Invalid credentials',
      'invalidEmail': 'Invalid email format',
      'userNotFound': 'No user found for that email',
      'wrongPassword': 'Wrong password provided',
      'emailAlreadyInUse': 'The email address is already in use',
      'weakPassword': 'The password is too weak',
      'registrationFailed': 'Registration failed. Please try again.',
      'dontHaveAccount': 'Don\'t have an account? Sign Up',
      'noJobsAvailable': 'No jobs available in this category',
      'company': 'Company',
      'location': 'Location',
      'home': 'Home',
      'search': 'Search',
      'notifications': 'Notifications',
      'profile': 'Profile',
      'categoryIT': 'IT',
      'categoryMarketing': 'Marketing',
      'categorySales': 'Sales',
      'categoryDesign': 'Design',
      'categoryHR': 'HR',
      'categoryFinance': 'Finance',
      'register': 'Register',
      'name': 'Name',
      'enterName': 'Please enter your name',
      'myResume': 'My Resume',
      'noResumes': 'No resumes added',
      'createResume': 'Create New Resume',
      'verifyYourself': 'Verify Yourself',
      'verified': 'Verified',
      'deletePhoto': 'Delete Photo',
      'cameraError': 'Failed to access camera',
      'statusActive': 'Actively looking for a job',
      'statusFound': 'Found a job',
      'statusNotLooking': 'Not looking for a job',
      'takePhoto': 'Take Photo',
      'cameraActive': 'Camera active. Press to capture.',
      'capture': 'Capture',
      'version': 'Version 1.0.0',
      'aboutUs': 'About Us',
      'aboutDescription':
          'The Job Recruitment Platform is designed to connect job seekers with employers seamlessly. Our mission is to simplify the job search process by providing a user-friendly interface, personalized job recommendations, and secure user management. Whether you\'re looking for your dream job or seeking top talent, our platform is here to help.',
      'features': 'Features',
      'jobSearch': 'Job Search',
      'jobSearchDescription':
          'Find jobs tailored to your skills and preferences.',
      'profileManagement': 'Profile Management',
      'profileManagementDescription':
          'Easily update your personal information and preferences.',
      'notificationsFeature': 'Notifications',
      'notificationsDescription':
          'Stay updated with job alerts and application statuses.',
      'copyright': '© 2025 Job Recruitment Platform. All rights reserved.',
      'contactSupportTitle': 'Contact Support',
      'supportDescription':
          'If you need assistance, please fill out the form below, and our support team will get back to you.',
      'subject': 'Subject',
      'enterSubject': 'Please enter a subject',
      'message': 'Message',
      'enterMessage': 'Please enter a message',
      'yourEmail': 'Your email',
      'sendMessage': 'Send Message',
      'messageSent': 'Message sent successfully!',
      'messageFailed': 'Failed to send message.',
      'error': 'Error',
      'userSettings': 'User Settings',
      'notificationSettings': 'Notification Settings',
      'favourites': 'Favourites',
      'languageKazakh': 'Қазақша',
      'languageRussian': 'Русский',
      'languageEnglish': 'English',
      'newName': 'New Name',
      'newPassword': 'New Password',
      'updateName': 'Update Name',
      'updatePassword': 'Update Password',
      'nameUpdated': 'Name updated successfully',
      'passwordUpdated': 'Password updated successfully',
      'enableSound': 'Enable Sound',
      'favouritesPlaceholder': 'Favourites settings will be implemented here.',
      'failedToOpenAbout': 'Failed to open About page',
      'failedToOpenHelp': 'Failed to open Help page',
      'continueAsGuest': 'Continue as Guest',
      'findYourDreamJob': 'Find Your Dream Job',
      'pleaseLogin': 'Please log in to access this feature',
      'selectRole': 'Select Your Role',
      'rolePrompt': 'Are you looking for a job or hiring talent?',
      'jobSeeker': 'Job Seeker',
      'employer': 'Employer',
      'whoAreYou': 'Who are you?',
      'pleaseSelectRole': 'Please select a role',
      'yourJobs': 'Your Jobs',
      'noJobsCreated': 'No jobs created yet',
      'createJob': 'Create Job',
      'resumeSavedSuccess': 'Resume saved successfully!',
      'resumeDeletedSuccess': 'Resume deleted successfully!',
      'userNotAuthenticated': 'User not authenticated',
      'fillAllFields': 'Please fill all fields',
      'editJobNotImplemented': 'Job editing is not implemented yet',
      'profession': 'Profession',
      'created': 'Created',
      'save': 'Save',
      'jobTitle': 'Job Title',
      'description': 'Description',
      'salary': 'Salary',
      'city': 'City',
      'schedule': 'Schedule',
      'employmentType': 'Employment Type',
      'en': 'Please connect to the internet',
      'requirements': 'Requirements',
      'contactInfo': 'Contact Info',
      'enterJobTitle': 'Please enter job title',
      'enterDescription': 'Please enter description',
      'registrationSuccess': "Successfully registered",
      'selectCategory': 'Please select a category',
      'enterSalary': 'Please enter salary',
      'enterCity': 'Please enter city',
      'selectSchedule': 'Please select a schedule',
      'selectEmploymentType': 'Please select employment type',
      'enterRequirements': 'Please enter requirements',
      'enterContactInfo': 'Please enter contact info',
      'scheduleFullTime': 'Full Time',
      'schedulePartTime': 'Part Time',
      'scheduleRemote': 'Remote',
      'scheduleFlexible': 'Flexible',
      'employmentFull': 'Full Employment',
      'employmentPart': 'Part Employment',
      'employmentContract': 'Contract',
      'employmentTemporary': 'Temporary',
      'editJob': 'Edit Job',
      'saveChanges': 'Save Changes',
      'jobUpdatedSuccess': 'Job updated successfully!',
      'category': 'Category',
    },
    'ru': {
      'connectToInternet': 'Подключитесь к интернету',
      'offlineModeWarning': 'Эта функция требует подключения к интернету',
      'yourVacancy': 'Это ваша вакансия',
      'apply': 'Откликнуться',
      'views': 'Просмотры',
      'applications': 'Заявки',
      'appliedJobs': 'Поданные заявки',
      'noApplications': 'Заявки пока не поданы',
      'submittedAt': 'Дата подачи',
      'coverLetter': 'Сопроводительное письмо',
      'resumeLink': 'Ссылка на резюме',
      'confirmDelete': 'Подтверждение удаления',
      'deleteJobConfirmation': 'Вы уверены, что хотите удалить эту вакансию?',
      'jobDeleted': 'Вакансия успешно удалена',
      'signOut': 'Выйти',
      'appTitle': 'Платформа для поиска работы',
      'welcomeBack': 'С возвращением!',
      'login': 'Войти',
      'signUp': 'Зарегистрироваться',
      'aboutTheApp': 'О приложении',
      'help': 'Помощь',
      'settings': 'Настройки',
      'language': 'Язык',
      'darkTheme': 'Темная тема',
      'logout': 'Выйти',
      'confirmLogout': 'Подтверждение выхода',
      'confirmLogoutMessage': 'Вы уверены, что хотите выйти?',
      'cancel': 'Отмена',
      'logoutFailed': 'Не удалось выйти из системы. Попробуйте снова.',
      'contactSupport': 'Связаться с поддержкой',
      'requestsProcessedSuccess': 'Ваши запросы успешно обработаны',
      'jobSeekerDashboard': 'Панель соискателя',
      'recentJobs': 'Недавние вакансии',
      'jobCategories': 'Категории вакансий',
      'noRecentJobs': 'Нет недавно просмотренных вакансий',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'enterEmail': 'Пожалуйста, введите вашу электронную почту',
      'enterPassword': 'Пожалуйста, введите ваш пароль',
      'invalidCredentials': 'Неверные учетные данные',
      'invalidEmail': 'Неверный формат электронной почты',
      'userNotFound': 'Пользователь с таким email не найден',
      'wrongPassword': 'Неверный пароль',
      'emailAlreadyInUse': 'Этот email уже используется',
      'weakPassword': 'Пароль слишком слабый',
      'registrationFailed': 'Регистрация не удалась. Попробуйте снова.',
      'dontHaveAccount': 'Нет аккаунта? Зарегистрируйтесь',
      'noJobsAvailable': 'В этой категории нет доступных вакансий',
      'company': 'Компания',
      'location': 'Местоположение',
      'home': 'Главная',
      'search': 'Поиск',
      'notifications': 'Уведомления',
      'profile': 'Профиль',
      'categoryIT': 'ИТ',
      'categoryMarketing': 'Маркетинг',
      'categorySales': 'Продажи',
      'categoryDesign': 'Дизайн',
      'categoryHR': 'HR',
      'categoryFinance': 'Финансы',
      'register': 'Зарегистрироваться',
      'name': 'Имя',
      'enterName': 'Пожалуйста, введите ваше имя',
      'myResume': 'Мое резюме',
      'noResumes': 'Нет добавленных резюме',
      'createResume': 'Создать новое резюме',
      'verifyYourself': 'Верифицировать себя',
      'verified': 'Верифицировано',
      'deletePhoto': 'Удалить фото',
      'cameraError': 'Не удалось получить доступ к камере',
      'statusActive': 'Активно ищу работу',
      'statusFound': 'Нашел работу',
      'statusNotLooking': 'Не ищу работу',
      'takePhoto': 'Сделать фото',
      'cameraActive': 'Камера активна. Нажмите, чтобы сделать снимок.',
      'capture': 'Снять',
      'version': 'Версия 1.0.0',
      'aboutUs': 'О нас',
      'aboutDescription':
          'Платформа для поиска работы создана для удобного соединения соискателей с работодателями. Наша миссия — упростить процесс поиска работы, предоставляя удобный интерфейс, персонализированные рекомендации по вакансиям и безопасное управление данными пользователей. Ищете ли вы работу мечты или талантливых специалистов, наша платформа здесь, чтобы помочь.',
      'features': 'Функции',
      'jobSearch': 'Поиск работы',
      'jobSearchDescription':
          'Находите вакансии, соответствующие вашим навыкам и предпочтениям.',
      'profileManagement': 'Управление профилем',
      'profileManagementDescription':
          'Легко обновляйте вашу личную информацию и настройки.',
      'notificationsFeature': 'Уведомления',
      'notificationsDescription':
          'Будьте в курсе с уведомлениями о вакансиях и статусах заявок.',
      'copyright': '© 2025 Платформа для поиска работы. Все права защищены.',
      'contactSupportTitle': 'Связаться с поддержкой',
      'supportDescription':
          'Если вам нужна помощь, заполните форму ниже, и наша команда поддержки свяжется с вами.',
      'subject': 'Тема',
      'enterSubject': 'Пожалуйста, введите тему',
      'message': 'Сообщение',
      'enterMessage': 'Пожалуйста, введите сообщение',
      'yourEmail': 'Ваш email',
      'sendMessage': 'Отправить сообщение',
      'messageSent': 'Сообщение успешно отправлено!',
      'messageFailed': 'Не удалось отправить сообщение.',
      'error': 'Ошибка',
      'userSettings': 'Настройки пользователя',
      'notificationSettings': 'Настройки уведомлений',
      'registrationSuccess': "Успешно зарегестрировано",
      'ru': 'Пожалуйста, подключитесь к интернету',
      'favourites': 'Избранное',
      'languageKazakh': 'Қазақша',
      'languageRussian': 'Русский',
      'languageEnglish': 'English',
      'newName': 'Новое имя',
      'newPassword': 'Новый пароль',
      'updateName': 'Обновить имя',
      'updatePassword': 'Обновить пароль',
      'nameUpdated': 'Имя успешно обновлено',
      'passwordUpdated': 'Пароль успешно обновлен',
      'enableSound': 'Включить звук',
      'favouritesPlaceholder': 'Здесь будут реализованы настройки избранного.',
      'failedToOpenAbout': 'Не удалось открыть страницу "О приложении"',
      'failedToOpenHelp': 'Не удалось открыть страницу "Помощь"',
      'continueAsGuest': 'Продолжить как гость',
      'findYourDreamJob': 'Найдите работу своей мечты',
      'pleaseLogin':
          'Пожалуйста, войдите, чтобы получить доступ к этой функции',
      'selectRole': 'Выберите вашу роль',
      'rolePrompt': 'Вы ищете работу или нанимаете специалистов?',
      'jobSeeker': 'Соискатель',
      'employer': 'Работодатель',
      'whoAreYou': 'Кто ты?',
      'pleaseSelectRole': 'Пожалуйста, выберите роль',
      'yourJobs': 'Ваши вакансии',
      'noJobsCreated': 'Пока не создано вакансий',
      'createJob': 'Создать вакансию',
      'resumeSavedSuccess': 'Резюме успешно сохранено!',
      'resumeDeletedSuccess': 'Резюме успешно удалено!',
      'userNotAuthenticated': 'Пользователь не аутентифицирован',
      'fillAllFields': 'Пожалуйста, заполните все поля',
      'editJobNotImplemented': 'Редактирование вакансии пока не реализовано',
      'profession': 'Профессия',
      'created': 'Создано',
      'save': 'Сохранить',
      'jobTitle': 'Название вакансии',
      'description': 'Описание',
      'salary': 'Зарплата',
      'city': 'Город',
      'schedule': 'График',
      'employmentType': 'Тип занятости',
      'requirements': 'Требования',
      'contactInfo': 'Контактная информация',
      'enterJobTitle': 'Пожалуйста, введите название вакансии',
      'enterDescription': 'Пожалуйста, введите описание',
      'selectCategory': 'Пожалуйста, выберите категорию',
      'enterSalary': 'Пожалуйста, введите зарплату',
      'enterCity': 'Пожалуйста, введите город',
      'selectSchedule': 'Пожалуйста, выберите график',
      'selectEmploymentType': 'Пожалуйста, выберите тип занятости',
      'enterRequirements': 'Пожалуйста, введите требования',
      'enterContactInfo': 'Пожалуйста, введите контактную информацию',
      'scheduleFullTime': 'Полный день',
      'schedulePartTime': 'Неполный день',
      'scheduleRemote': 'Удаленная работа',
      'scheduleFlexible': 'Гибкий график',
      'employmentFull': 'Полная занятость',
      'employmentPart': 'Частичная занятость',
      'employmentContract': 'Контракт',
      'employmentTemporary': 'Временная',
      'editJob': 'Редактировать вакансию',
      'saveChanges': 'Сохранить изменения',
      'jobUpdatedSuccess': 'Вакансия успешно обновлена!',
      'category': 'Категория',
    },
    'kk': {
      'connectToInternet': 'Интернетке қосылыңыз',
      'offlineModeWarning': 'Бұл функция интернет қосылымын қажет етеді',
      'yourVacancy': 'Бұл сіздің бос орныңыз',
      'apply': 'Өтініш беру',
      'views': 'Қаралымдар',
      'applications': 'Өтініштер',
      'appliedJobs': 'Жіберілген өтініштер',
      'noApplications': 'Әзірге өтініштер жіберілмеген',
      'submittedAt': 'Жіберілген уақыт',
      'coverLetter': 'Ілеспе хат',
      'resumeLink': 'Резюме сілтемесі',
      'confirmDelete': 'Жоюды растау',
      'deleteJobConfirmation':
          'Бұл бос орынды жойғыңыз келетініне сенімдісіз бе?',
      'jobDeleted': 'Бос орын сәтті жойылды',
      'signOut': 'Шығу',
      'appTitle': 'Жұмыс іздеу платформасы',
      'welcomeBack': 'Қайта оралуыңызбен!',
      'login': 'Кіру',
      'signUp': 'Тіркелу',
      'aboutTheApp': 'Қосымша туралы',
      'help': 'Көмек',
      'settings': 'Параметрлер',
      'language': 'Тіл',
      'darkTheme': 'Қараңғы тақырып',
      'logout': 'Шығу',
      'confirmLogout': 'Шығуды растау',
      'confirmLogoutMessage': 'Сіз шығуға сенімдісіз бе?',
      'cancel': 'Болдырмау',
      'logoutFailed': 'Жүйеден шығу сәтсіз аяқталды. Қайтадан көріңіз.',
      'contactSupport': 'Қолдау қызметіне хабарласу',
      'jobSeekerDashboard': 'Жұмыс іздеуші панелі',
      'recentJobs': 'Соңғы жұмыс орындары',
      'jobCategories': 'Жұмыс категориялары',
      'noRecentJobs': 'Жақында қаралған жұмыс орындары жоқ',
      'email': 'Электрондық пошта',
      'password': 'Құпия сөз',
      'enterEmail': 'Электрондық поштаңызды енгізіңіз',
      'enterPassword': 'Құпия сөзіңізді енгізіңіз',
      'invalidCredentials': 'Жарамсыз мәліметтер',
      'invalidEmail': 'Электрондық пошта форматы жарамсыз',
      'userNotFound': 'Бұл email үшін пайдаланушы табылмады',
      'requestsProcessedSuccess': 'Сіздің сұрауларыңыз сәтті өңделді',
      'wrongPassword': 'Қате құпия сөз енгізілді',
      'emailAlreadyInUse': 'Бұл email адресі әлдеқашан қолданылуда',
      'weakPassword': 'Құпия сөз тым әлсіз',
      'registrationFailed': 'Тіркеу сәтсіз аяқталды. Қайтадан көріңіз.',
      'dontHaveAccount': 'Есептік жазбаңыз жоқ па? Тіркеліңіз',
      'noJobsAvailable': 'Бұл санатта жұмыс орындары жоқ',
      'company': 'Компания',
      'location': 'Орналасу',
      'home': 'Басты',
      'search': 'Іздеу',
      'notifications': 'Хабарламалар',
      'profile': 'Профиль',
      'categoryIT': 'АҚТ',
      'categoryMarketing': 'Маркетинг',
      'categorySales': 'Сату',
      'categoryDesign': 'Дизайн',
      'categoryHR': 'Кадрлар',
      'categoryFinance': 'Қаржы',
      'register': 'Тіркелу',
      'name': 'Аты',
      'enterName': 'Атыңызды енгізіңіз',
      'myResume': 'Менің түйіндемем',
      'noResumes': 'Түйіндемелер қосылмаған',
      'createResume': 'Жаңа түйіндеме жасау',
      'verifyYourself': 'Өзіңізді верификациялау',
      'verified': 'Верификацияланған',
      'deletePhoto': 'Фотуды жою',
      'cameraError': 'Камераға кіру мүмкін болмады',
      'statusActive': 'Жұмыс іздеп жатырмын',
      'statusFound': 'Жұмыс таптым',
      'statusNotLooking': 'Жұмыс іздемеймін',
      'takePhoto': 'Фото жасау',
      'cameraActive': 'Камера белсенді. Суретке түсіру үшін басыңыз.',
      'capture': 'Түсіру',
      'version': 'Нұсқа 1.0.0',
      'aboutUs': 'Біз туралы',
      'aboutDescription':
          'Жұмыс іздеу платформасы жұмыс іздеушілерді жұмыс берушілермен оңай байланыстыруға арналған. Біздің миссиямыз — пайдаланушыға ыңғайлы интерфейс, жеке ұсынылған вакансиялар және қауіпсіз деректерді басқару арқылы жұмыс іздеу процесін жеңілдету. Армандаған жұмысыңызды іздесеңіз немесе талантты мамандарды іздесеңіз, біздің платформа сізге көмектеседі.',
      'features': 'Мүмкіндіктер',
      'jobSearch': 'Жұмыс іздеу',
      'jobSearchDescription':
          'Сіздің дағдыларыңыз бен қалауларыңызға сәйкес вакансияларды табыңыз.',
      'profileManagement': 'Профильді басқару',
      'profileManagementDescription':
          'Жеке ақпаратыңызды және параметрлеріңізді оңай жаңартыңыз.',
      'notificationsFeature': 'Хабарламалар',
      'notificationsDescription':
          'Жұмыс туралы хабарламалар және өтінімдердің күйі туралы хабардар болыңыз.',
      'copyright': '© 2025 Жұмыс іздеу платформасы. Барлық құқықтар қорғалған.',
      'contactSupportTitle': 'Қолдау қызметіне хабарласу',
      'supportDescription':
          'Егер сізге көмек қажет болса, төмендегі форманы толтырыңыз, және біздің қолдау тобы сізге жауап береді.',
      'subject': 'Тақырып',
      'enterSubject': 'Тақырыпты енгізіңіз',
      'message': 'Хабарлама',
      'enterMessage': 'Хабарламаны енгізіңіз',
      'yourEmail': 'Сіздің email',
      'sendMessage': 'Хабарлама жіберу',
      'messageSent': 'Хабарлама сәтті жіберілді!',
      'messageFailed': 'Хабарламаны жіберу мүмкін болмады.',
      'error': 'Қате',
      'userSettings': 'Пайдаланушы параметрлері',
      'notificationSettings': 'Хабарламалар параметрлері',
      'favourites': 'Таңдаулылар',
      'languageKazakh': 'Қазақша',
      'languageRussian': 'Русский',
      'languageEnglish': 'English',
      'newName': 'Жаңа аты',
      'newPassword': 'Жаңа құпия сөз',
      'updateName': 'Атын жаңарту',
      'updatePassword': 'Құпия сөзді жаңарту',
      'nameUpdated': 'Аты сәтті жаңартылды',
      'passwordUpdated': 'Құпия сөз сәтті жаңартылды',
      'enableSound': 'Дыбысты қосу',
      'kk': 'Интернетке қосылыңыз',
      'favouritesPlaceholder': 'Мұнда таңдаулылар параметрлері іске асырылады.',
      'failedToOpenAbout': 'Қосымша туралы бетті ашу мүмкін болмады',
      'failedToOpenHelp': 'Көмек бетін ашу мүмкін болмады',
      'continueAsGuest': 'Қонақ ретінде жалғастыру',
      'findYourDreamJob': 'Арманыңыздағы жұмысты табыңыз',
      'pleaseLogin': 'Бұл функцияға кіру үшін жүйеге кіріңіз',
      'selectRole': 'Рөліңізді таңдаңыз',
      'rolePrompt':
          'Сіз жұмыс іздеп жатырсыз ба, әлде мамандар жалдап жатырсыз ба?',
      'jobSeeker': 'Жұмыс іздеуші',
      'employer': 'Жұмыс беруші',
      'whoAreYou': 'Сен кимсиң?',
      'pleaseSelectRole': 'Рөлді таңдаңыз',
      'yourJobs': 'Сіздің вакансияларыңыз',
      'noJobsCreated': 'Әзірге вакансиялар жасалмаған',
      'createJob': 'Вакансия жасау',
      'resumeSavedSuccess': 'Түйіндеме сәтті сақталды!',
      'resumeDeletedSuccess': 'Түйіндеме сәтті жойылды!',
      'userNotAuthenticated': 'Пайдаланушы аутентификацияланбаған',
      'fillAllFields': 'Барлық өрістерді толтырыңыз',
      'editJobNotImplemented': 'Вакансияны өңдеу әлі іске асырылмаған',
      'profession': 'Мамандық',
      'created': 'Жасалған',
      'save': 'Сақтау',
      'jobTitle': 'Вакансия атауы',
      'description': 'Сипаттама',
      'salary': 'Жалақы',
      'city': 'Қала',
      'schedule': 'Кесте',
      'employmentType': 'Жұмыс түрі',
      'requirements': 'Талаптар',
      'contactInfo': 'Байланыс ақпараты',
      'enterJobTitle': 'Вакансия атауын енгізіңіз',
      'enterDescription': 'Сипаттаманы енгізіңіз',
      'selectCategory': 'Категорияны таңдаңыз',
      'enterSalary': 'Жалақыны енгізіңіз',
      'enterCity': 'Қаланы енгізіңіз',
      'selectSchedule': 'Кестені таңдаңыз',
      'selectEmploymentType': 'Жұмыс түрін таңдаңыз',
      'enterRequirements': 'Талаптарды енгізіңіз',
      'enterContactInfo': 'Байланыс ақпаратын енгізіңіз',
      'scheduleFullTime': 'Толық күн',
      'schedulePartTime': 'Жарты күн',
      'scheduleRemote': 'Қашықтан жұмыс',
      'scheduleFlexible': 'Икемді кесте',
      'employmentFull': 'Толық жұмыс',
      'employmentPart': 'Жартылай жұмыс',
      'employmentContract': 'Келісімшарт',
      'employmentTemporary': 'Уақытша',
      'editJob': 'Вакансияны өңдеу',
      'saveChanges': 'Өзгерістерді сақтау',
      'jobUpdatedSuccess': 'Вакансия сәтті жаңартылды!',
      'category': 'Категория',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('ru'));
  }

  String translate(String key) {
    return _translations[locale.languageCode]?[key] ??
        _translations['ru']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ru', 'kk'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
