import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // Существующие переводы (из предыдущих ответов)
      'appTitle': 'Job Recruitment Platform',
      'welcomeBack': 'Welcome Back!',
      'login': 'Login',
      'signUp': 'Sign Up',
      'aboutTheApp': 'About the App',
      'help': 'Help',
      'settings': 'Settings',
      'language': 'Language',
      'darkTheme': 'Dark Theme',
      'logout': 'Logout',
      'contactSupport': 'Contact Support',
      'jobSeekerDashboard': 'Job Seeker Dashboard',
      'recentJobs': 'Recent Jobs',
      'jobCategories': 'Job Categories',
      'noRecentJobs': 'No recently viewed jobs',
      'email': 'Email',
      'password': 'Password',
      'enterEmail': 'Please enter your email',
      'enterPassword': 'Please enter your password',
      'invalidCredentials': 'Invalid credentials',
      'dontHaveAccount': 'Don\'t have an account? Sign Up',
      'noJobsAvailable': 'No jobs available in this category',
      'company': 'Company',
      'location': 'Location',
      'home': 'Home',
      'search': 'Search',
      'notifications': 'Notifications',
      'profile': 'Profile',
      'categoryIT': 'IT',
      'categoryMarketing': 'Marketing',
      'categorySales': 'Sales',
      'categoryDesign': 'Design',
      'categoryHR': 'HR',
      'categoryFinance': 'Finance',
      'register': 'Register',
      'name': 'Name',
      'enterName': 'Please enter your name',
      'myResume': 'My Resume',
      'noResumes': 'No resumes added',
      'createResume': 'Create New Resume',
      'verifyYourself': 'Verify Yourself',
      'verified': 'Verified',
      'deletePhoto': 'Delete Photo',
      'cameraError': 'Failed to access camera',
      'statusActive': 'Actively looking for a job',
      'statusFound': 'Found a job',
      'statusNotLooking': 'Not looking for a job',
      'takePhoto': 'Take Photo',
      'cameraActive': 'Camera is active. Press to take a photo.',
      'cancel': 'Cancel',
      'version': 'Version 1.0.0',
      'aboutUs': 'About Us',
      'aboutDescription':
          'The Job Recruitment Platform is designed to connect job seekers with employers seamlessly. Our mission is to simplify the job search process by providing a user-friendly interface, personalized job recommendations, and secure user management. Whether you\'re looking for your dream job or seeking top talent, our platform is here to help.',
      'features': 'Features',
      'jobSearch': 'Job Search',
      'jobSearchDescription': 'Find jobs tailored to your skills and preferences.',
      'profileManagement': 'Profile Management',
      'profileManagementDescription':
          'Easily update your personal information and preferences.',
      'notificationsFeature': 'Notifications',
      'notificationsDescription':
          'Stay updated with job alerts and application statuses.',
      'copyright': '© 2025 Job Recruitment Platform. All rights reserved.',
      'contactSupportTitle': 'Contact Support',
      'supportDescription':
          'If you need assistance, please fill out the form below, and our support team will get back to you.',
      'subject': 'Subject',
      'enterSubject': 'Please enter a subject',
      'message': 'Message',
      'enterMessage': 'Please enter a message',
      'yourEmail': 'Your email',
      'sendMessage': 'Send Message',
      'messageSent': 'Message sent successfully!',
      'messageFailed': 'Failed to send message.',
      'error': 'Error',
      // Новые переводы для SettingsPage и связанных страниц
      'userSettings': 'User Settings',
      'notificationSettings': 'Notification Settings',
      'favourites': 'Favourites',
      'languageKazakh': 'Kazakh',
      'languageRussian': 'Russian',
      'languageEnglish': 'English',
      'newName': 'New Name',
      'newPassword': 'New Password',
      'updateName': 'Update Name',
      'updatePassword': 'Update Password',
      'nameUpdated': 'Name updated successfully',
      'passwordUpdated': 'Password updated successfully',
      'enableSound': 'Enable Sound',
      'favouritesPlaceholder': 'Favourites settings will be implemented here.',
      'failedToOpenAbout': 'Failed to open About page',
      'failedToOpenHelp': 'Failed to open Help page',
    },
    'ru': {
      // Существующие переводы
      'appTitle': 'Платформа для поиска работы',
      'welcomeBack': 'С возвращением!',
      'login': 'Войти',
      'signUp': 'Зарегистрироваться',
      'aboutTheApp': 'О приложении',
      'help': 'Помощь',
      'settings': 'Настройки',
      'language': 'Язык',
      'darkTheme': 'Темная тема',
      'logout': 'Выйти',
      'contactSupport': 'Связаться с поддержкой',
      'jobSeekerDashboard': 'Панель соискателя',
      'recentJobs': 'Недавние вакансии',
      'jobCategories': 'Категории вакансий',
      'noRecentJobs': 'Нет недавно просмотренных вакансий',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'enterEmail': 'Пожалуйста, введите вашу электронную почту',
      'enterPassword': 'Пожалуйста, введите ваш пароль',
      'invalidCredentials': 'Неверные учетные данные',
      'dontHaveAccount': 'Нет аккаунта? Зарегистрируйтесь',
      'noJobsAvailable': 'В этой категории нет доступных вакансий',
      'company': 'Компания',
      'location': 'Местоположение',
      'home': 'Главная',
      'search': 'Поиск',
      'notifications': 'Уведомления',
      'profile': 'Профиль',
      'categoryIT': 'ИТ',
      'categoryMarketing': 'Маркетинг',
      'categorySales': 'Продажи',
      'categoryDesign': 'Дизайн',
      'categoryHR': 'HR',
      'categoryFinance': 'Финансы',
      'register': 'Зарегистрироваться',
      'name': 'Имя',
      'enterName': 'Пожалуйста, введите ваше имя',
      'myResume': 'Мое резюме',
      'noResumes': 'Нет добавленных резюме',
      'createResume': 'Создать новое резюме',
      'verifyYourself': 'Верифицировать себя',
      'verified': 'Верифицировано',
      'deletePhoto': 'Удалить фото',
      'cameraError': 'Не удалось получить доступ к камере',
      'statusActive': 'Активно ищу работу',
      'statusFound': 'Нашел работу',
      'statusNotLooking': 'Не ищу работу',
      'takePhoto': 'Сделать фото',
      'cameraActive': 'Камера активна. Нажмите, чтобы сделать снимок.',
      'cancel': 'Отмена',
      'version': 'Версия 1.0.0',
      'aboutUs': 'О нас',
      'aboutDescription':
          'Платформа для поиска работы создана для удобного соединения соискателей с работодателями. Наша миссия — упростить процесс поиска работы, предоставляя удобный интерфейс, персонализированные рекомендации по вакансиям и безопасное управление данными пользователей. Ищете ли вы работу мечты или талантливых специалистов, наша платформа здесь, чтобы помочь.',
      'features': 'Функции',
      'jobSearch': 'Поиск работы',
      'jobSearchDescription':
          'Находите вакансии, соответствующие вашим навыкам и предпочтениям.',
      'profileManagement': 'Управление профилем',
      'profileManagementDescription':
          'Легко обновляйте вашу личную информацию и настройки.',
      'notificationsFeature': 'Уведомления',
      'notificationsDescription':
          'Будьте в курсе с уведомлениями о вакансиях и статусах заявок.',
      'copyright': '© 2025 Платформа для поиска работы. Все права защищены.',
      'contactSupportTitle': 'Связаться с поддержкой',
      'supportDescription':
          'Если вам нужна помощь, заполните форму ниже, и наша команда поддержки свяжется с вами.',
      'subject': 'Тема',
      'enterSubject': 'Пожалуйста, введите тему',
      'message': 'Сообщение',
      'enterMessage': 'Пожалуйста, введите сообщение',
      'yourEmail': 'Ваш email',
      'sendMessage': 'Отправить сообщение',
      'messageSent': 'Сообщение успешно отправлено!',
      'messageFailed': 'Не удалось отправить сообщение.',
      'error': 'Ошибка',
      // Новые переводы для SettingsPage и связанных страниц
      'userSettings': 'Настройки пользователя',
      'notificationSettings': 'Настройки уведомлений',
      'favourites': 'Избранное',
      'languageKazakh': 'Қазақша',
      'languageRussian': 'Русский',
      'languageEnglish': 'English',
      'newName': 'Новое имя',
      'newPassword': 'Новый пароль',
      'updateName': 'Обновить имя',
      'updatePassword': 'Обновить пароль',
      'nameUpdated': 'Имя успешно обновлено',
      'passwordUpdated': 'Пароль успешно обновлен',
      'enableSound': 'Включить звук',
      'favouritesPlaceholder': 'Здесь будут реализованы настройки избранного.',
      'failedToOpenAbout': 'Не удалось открыть страницу "О приложении"',
      'failedToOpenHelp': 'Не удалось открыть страницу "Помощь"',
    },
    'kk': {
      // Существующие переводы
      'appTitle': 'Жұмыс іздеу платформасы',
      'welcomeBack': 'Қайта оралуыңызбен!',
      'login': 'Кіру',
      'signUp': 'Тіркелу',
      'aboutTheApp': 'Қосымша туралы',
      'help': 'Көмек',
      'settings': 'Параметрлер',
      'language': 'Тіл',
      'darkTheme': 'Қараңғы тақырып',
      'logout': 'Шығу',
      'contactSupport': 'Қолдау қызметіне хабарласу',
      'jobSeekerDashboard': 'Жұмыс іздеуші панелі',
      'recentJobs': 'Соңғы жұмыс орындары',
      'jobCategories': 'Жұмыс категориялары',
      'noRecentJobs': 'Жақында қаралған жұмыс орындары жоқ',
      'email': 'Электрондық пошта',
      'password': 'Құпия сөз',
      'enterEmail': 'Электрондық поштаңызды енгізіңіз',
      'enterPassword': 'Құпия сөзіңізді енгізіңіз',
      'invalidCredentials': 'Жарамсыз мәліметтер',
      'dontHaveAccount': 'Есептік жазбаңыз жоқ па? Тіркеліңіз',
      'noJobsAvailable': 'Бұл санатта жұмыс орындары жоқ',
      'company': 'Компания',
      'location': 'Орналасу',
      'home': 'Басты',
      'search': 'Іздеу',
      'notifications': 'Хабарламалар',
      'profile': 'Профиль',
      'categoryIT': 'АҚТ',
      'categoryMarketing': 'Маркетинг',
      'categorySales': 'Сату',
      'categoryDesign': 'Дизайн',
      'categoryHR': 'Кадрлар',
      'categoryFinance': 'Қаржы',
      'register': 'Тіркелу',
      'name': 'Аты',
      'enterName': 'Атыңызды енгізіңіз',
      'myResume': 'Менің түйіндемем',
      'noResumes': 'Түйіндемелер қосылмаған',
      'createResume': 'Жаңа түйіндеме жасау',
      'verifyYourself': 'Өзіңізді верификациялау',
      'verified': 'Верификацияланған',
      'deletePhoto': 'Фотуды жою',
      'cameraError': 'Камераға кіру мүмкін болмады',
      'statusActive': 'Жұмыс іздеп жатырмын',
      'statusFound': 'Жұмыс таптым',
      'statusNotLooking': 'Жұмыс іздемеймін',
      'takePhoto': 'Фото жасау',
      'cameraActive': 'Камера белсенді. Суретке түсіру үшін басыңыз.',
      'cancel': 'Болдырмау',
      'version': 'Нұсқа 1.0.0',
      'aboutUs': 'Біз туралы',
      'aboutDescription':
          'Жұмыс іздеу платформасы жұмыс іздеушілерді жұмыс берушілермен оңай байланыстыруға арналған. Біздің миссиямыз — пайдаланушыға ыңғайлы интерфейс, жеке ұсынылған вакансиялар және қауіпсіз деректерді басқару арқылы жұмыс іздеу процесін жеңілдету. Армандаған жұмысыңызды іздесеңіз немесе талантты мамандарды іздесеңіз, біздің платформа сізге көмектеседі.',
      'features': 'Мүмкіндіктер',
      'jobSearch': 'Жұмыс іздеу',
      'jobSearchDescription':
          'Сіздің дағдыларыңыз бен қалауларыңызға сәйкес вакансияларды табыңыз.',
      'profileManagement': 'Профильді басқару',
      'profileManagementDescription':
          'Жеке ақпаратыңызды және параметрлеріңізді оңай жаңартыңыз.',
      'notificationsFeature': 'Хабарламалар',
      'notificationsDescription':
          'Жұмыс туралы хабарламалар және өтінімдердің күйі туралы хабардар болыңыз.',
      'copyright': '© 2025 Жұмыс іздеу платформасы. Барлық құқықтар қорғалған.',
      'contactSupportTitle': 'Қолдау қызметіне хабарласу',
      'supportDescription':
          'Егер сізге көмек қажет болса, төмендегі форманы толтырыңыз, және біздің қолдау тобы сізге жауап береді.',
      'subject': 'Тақырып',
      'enterSubject': 'Тақырыпты енгізіңіз',
      'message': 'Хабарлама',
      'enterMessage': 'Хабарламаны енгізіңіз',
      'yourEmail': 'Сіздің email',
      'sendMessage': 'Хабарлама жіберу',
      'messageSent': 'Хабарлама сәтті жіберілді!',
      'messageFailed': 'Хабарламаны жіберу мүмкін болмады.',
      'error': 'Қате',
      // Новые переводы для SettingsPage и связанных страниц
      'userSettings': 'Пайдаланушы параметрлері',
      'notificationSettings': 'Хабарламалар параметрлері',
      'favourites': 'Таңдаулылар',
      'languageKazakh': 'Қазақша',
      'languageRussian': 'Русский',
      'languageEnglish': 'English',
      'newName': 'Жаңа аты',
      'newPassword': 'Жаңа құпия сөз',
      'updateName': 'Атын жаңарту',
      'updatePassword': 'Құпия сөзді жаңарту',
      'nameUpdated': 'Аты сәтті жаңартылды',
      'passwordUpdated': 'Құпия сөз сәтті жаңартылды',
      'enableSound': 'Дыбысты қосу',
      'favouritesPlaceholder': 'Мұнда таңдаулылар параметрлері іске асырылады.',
      'failedToOpenAbout': 'Қосымша туралы бетті ашу мүмкін болмады',
      'failedToOpenHelp': 'Көмек бетін ашу мүмкін болмады',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String translate(String key) {
    return _translations[locale.languageCode]?[key] ?? _translations['en']![key]!;
  }
}